services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: web-store-backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend/uploads:/var/www/uploads
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: web-store-frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend/src/assets/images:/usr/src/app/images
    depends_on:
      - backend

  db:
    image: postgres:14
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: webstore
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/sql/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
